global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: mihomo-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - mihomo-exporter:9109
